name: Build and upload to Maestro Cloud (Native Android)

on: workflow_dispatch

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest
    outputs:
      app: android/app/build/outputs/apk/release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - run: yarn install
      - run: cd android && ./gradlew assembleRelease
      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: android/app/build/outputs/apk/release/app-release.apk
          env: |
            APPID=com.gitproject
