name: Build and upload to Maestro Cloud (Native iOS)

on: workflow_dispatch

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn install
      - run: |
          cd ios
          pod install
      - run: |
          cd ios
          xcodebuild -workspace 'GitProject.xcworkspace' -scheme 'GitProject' -configuration Debug -destination 'generic/platform=iOS Simulator' -derivedDataPath build
      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: ios/build//Build/Products/Debug-iphonesimulator/GitProject.app
          env: |
            APPID=org.reactjs.native.example.GitProject
